import pandas as pd
import vertexai
from google.cloud import aiplatform
from vertexai.evaluation import EvalTask, PointwiseMetric, PointwiseMetricPromptTemplate
from google import genai
import json

qa_quality_template = PointwiseMetricPromptTemplate(
    criteria={
        "Technical Accuracy (Semantic Precision)": "The generated Natural Language (NL) question perfectly reflects the underlying logic, operations (e.g., aggregations, filters, groupings), and data constraints present in the SQL query and the Result Summary. It balances code efficiency with semantic precision by neither hallucinating missing logic nor ignoring existing logic.",
        "Persona Alignment": "The tone, vocabulary, and framing of the NL question accurately match the provided Persona and its description (e.g., an executive asking high-level strategic questions vs. a data engineer asking about raw metrics).",
        "Fluency": "The question is grammatically correct, well-organized, and reads naturally to a human."
    },
    rating_rubric={
        "5": "(Excellent). The NL question perfectly translates the SQL logic and Result Summary with high semantic precision. It flawlessly embodies the specified Persona's tone and vocabulary. The phrasing is completely grounded, accurate, and fluent.",
        "4": "(Good). The NL question accurately reflects the primary SQL logic and Result Summary, and aligns well with the Persona. It is grounded and complete, but might lack slight semantic elegance or have minor stylistic imperfections regarding the persona.",
        "3": "(Fair). The NL question captures the general intent but misses specific SQL constraints (e.g., ignores a specific WHERE filter or GROUP BY aggregation). The alignment with the Persona is weak, inconsistent, or overly generic.",
        "2": "(Poor). The NL question fundamentally misinterprets the SQL logic, misrepresents the Result Summary, or is completely out of character for the target Persona. It lacks technical accuracy.",
        "1": "(Very Poor). The NL question is completely wrong, hallucinates information not present in the triplet, and is entirely disconnected from the provided SQL, Result Summary, and Persona."
    },
    instruction="""
    You are an expert evaluator. Your task is to evaluate the quality of the natural language questions generated by AI models.
    We will provide you with the user prompt (which contains the SQL, Result Summary, and Persona) and the AI-generated response.
    
    You should first read the user prompt carefully to analyze the task, and then evaluate the quality of the response based on the rules provided in the Evaluation section below.
    
    # Evaluation
    ## Criteria
    "Technical Accuracy (Semantic Precision)": "The generated Natural Language (NL) question perfectly reflects the underlying logic, operations (e.g., aggregations, filters, groupings), and data constraints present in the SQL query and the Result Summary. It balances code efficiency with semantic precision by neither hallucinating missing logic nor ignoring existing logic.",
    "Persona Alignment": "The tone, vocabulary, and framing of the NL question accurately match the provided Persona and its description (e.g., an executive asking high-level strategic questions vs. a data engineer asking about raw metrics).",
    "Fluency": "The question is grammatically correct, well-organized, and reads naturally to a human."
    
    ## Rating Rubric
    "5": "(Excellent). The NL question perfectly translates the SQL logic and Result Summary with high semantic precision. It flawlessly embodies the specified Persona's tone and vocabulary. The phrasing is completely grounded, accurate, and fluent.",
    "4": "(Good). The NL question accurately reflects the primary SQL logic and Result Summary, and aligns well with the Persona. It is grounded and complete, but might lack slight semantic elegance or have minor stylistic imperfections regarding the persona.",
    "3": "(Fair). The NL question captures the general intent but misses specific SQL constraints (e.g., ignores a specific WHERE filter or GROUP BY aggregation). The alignment with the Persona is weak, inconsistent, or overly generic.",
    "2": "(Poor). The NL question fundamentally misinterprets the SQL logic, misrepresents the Result Summary, or is completely out of character for the target Persona. It lacks technical accuracy.",
    "1": "(Very Poor). The NL question is completely wrong, hallucinates information not present in the triplet, and is entirely disconnected from the provided SQL, Result Summary, and Persona."
    
    ## Evaluation Steps
    STEP 1: Assess Technical Accuracy. Does the generated question capture all aggregations, filters, and logic in the SQL without hallucinating?
    STEP 2: Assess Persona Alignment. Does the tone and vocabulary match the requested persona?
    STEP 3: Assess Fluency. Is the generated question grammatically correct and natural to read?
    STEP 4: Output your step-by-step explanation based on the first 3 steps, and then finally assign a score based on the Rating Rubric. Only choose scores from 5, 4, 3, 2, 1.
    
    # User Inputs
    ## Prompt
    {prompt}
    
    ## AI-generated Response
    {response}
    """
)

# Initialize the metric
qa_quality_metric = PointwiseMetric(
    metric="custom_qa_quality",
    metric_prompt_template=qa_quality_template
)

def run_stage_3_evaluation(final_golden_data, experiment_name="sql-to-nl-eval-run"):

    # Prepare evaluation data
    eval_data = pd.DataFrame(final_golden_data)
    
    eval_records = eval_data[['system_prompt', 'nl_question']]
    # Rename columns to match what Vertex AI evaluator expects ('prompt' and 'response')
    eval_records = eval_records.rename(columns={'system_prompt': 'prompt', 'nl_question': 'response'})
    print(eval_records)
    eval_data = pd.DataFrame(eval_records)
    print(f"\n--- Evaluation Dataset Ready ({len(eval_data)} samples) ---")
    
    # Initialize Vertex AI for Evaluation
    vertexai.init(project="sl-test-project-353312", location="us-central1")

    # Set up EvalTask
    eval_task = EvalTask(
        dataset=eval_data,
        metrics=[qa_quality_metric],
        experiment=experiment_name
    )

    # Execute the LLM judge (omit model since response is included in the dataset)
    print("Evaluating Stage 2 outputs using LLM as a judge...")
    result = eval_task.evaluate()

    # Print out metrics and the LLM's step-by-step reasoning
    print("\n--- Evaluation Summary Metrics ---")
    print(result.summary_metrics)
    
    print("\n--- Detailed Evaluation Table ---")
    print(result.metrics_table)

    
    return result

if __name__ == "__main__":
    # Load Stage 2 output for standalone testing
    with open('stage2_results.json', 'r') as f:
        golden_data = json.load(f)
    run_stage_3_evaluation(golden_data)