
runtime: python
env: flex

service: dbai

env_variables:
  FLASK_APP: app.py

entrypoint: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"
