runtime: python
env: flex

service: nl2sqlstudio-ui

entrypoint: streamlit run nl2sqlstudio_ui.py --server.port=8080 --server.address=0.0.0.0

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11.2"
