#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Python Code (flake8)

on:
  push:
    branches-ignore: [main]  # Remove if you want to lint on pushes to main
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Lint Python Code (flake8)
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: \.py$  # Only include Python files
          FILTER_REGEX_EXCLUDE: nl2sql_library/ # Exclude this directory
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_FLAKE8: true  # Enable only flake8
